### ISSUE TITLE
Recuperar tema das proposiçoes

### ISSUE THREAD

**Issue by gabrielalbino** [parlamentaqui/gateway#30]
Implementar no ETL_Camara a lógica para recuperar o "tema" e repectivos campos não encontrados anteriormente de cada proposição e salvar no banco de dados.

**Comment by lmmLucasMachado** [comment]
Atributos e local da api camara onde é encontrado os respectivos campos:

- [Link API.](https://dadosabertos.camara.leg.br/swagger/api.html)

proposicao_id	        <---	/proposicoes
idDeputadoAutor	<---       /proposicoes ou /proposicoes/{id}
uri			          <--- 	/proposicoes/{id}
descricaoTipo   	<---	/proposicoes/{id}
ementa		             <--- 	/proposicoes/{id}
ementaDetalhada (explicacaoEmenta)	<---/proposicoes/{id}
keywords			  <---     /proposicoes/{id}
dataApresentacao      <---	/proposicoes/{id}
urlAutor			        <---/proposicoes/{id}/autores
tipoAutor		       <---     	/proposicoes/{id}/autores
nomeAutor	        <---	/proposicoes/{id}/autores
siglaUFAutor	        <---	/proposicoes/{id}/autores
temaProposicao      <---	/proposicoes/{id}/temas
status		        <---	/proposicoes/{id}
siglaOrgao	         <---	/proposicoes/{id}
data_proposicao (dataInicio)  <--- /proposicoes/{id}
descricaoSituacao	      <---  /proposicoes
despacho <---	         	/proposicoes
uriRelator	<---         	/proposicoes{id}
