### ISSUE TITLE
[BUG] Tweets da home não são os mais recentes

### ISSUE THREAD

**Issue by gabrielalbino** [parlamentaqui/gateway#35]
Os tweets trazidos para a home não são os mais recentes, conforme evidencias abaixo:
![image](https://user-images.githubusercontent.com/30835149/117369398-3ce90480-ae9b-11eb-86b9-f08a33e6f61b.png)

**Comment by jplyra** [comment]
Arrumei isso na issue 38 de refatorar os etls 😄
