### ISSUE TITLE
Criar endpoint para a retornar deputados da home

### ISSUE THREAD

**Issue by gabrielalbino** [parlamentaqui/gateway#4]
|EP1|FE01|US01|Eu, Konan, desejo ter acesso aos deputados com atividade recente na página inicial para que tenha acesso rápido a conteúdos relevantes.|

Referências:
- https://www.figma.com/file/UWBRoMSkFlLrO0S0t9yHFc/Parlamentaqui?node-id=1%3A529

Critérios de aceitação: 
- [x] Deve trazer todos os dados necessários para a apresentação do componente conforme o figma
- [x] Deve trazer a lista ordenada por data da ultiam atividade
- [x] Deve trazer as informações do banco de dados
- [x] O retorno do endpoint deve ser em json

**Comment by helenagoulart** [comment]
5
