### ISSUE TITLE
Criar endpoint para a ultimas noticias da home

### ISSUE THREAD

**Issue by gabrielalbino** [parlamentaqui/gateway#5]
US52|Eu, Eren, desejo conseguir ver informações armazenadas sobre notícias para ficar mais próximo da funcionalidade final.|

Referências:
- https://www.figma.com/file/UWBRoMSkFlLrO0S0t9yHFc/Parlamentaqui?node-id=1%3A529

Critérios de aceitação: 
- [x] Deve trazer todos os dados necessários para o componente funcionar conforme o figma.
- [x] Deve trazer apenas as 2 notícias mais recentes.
- [x] Deve recuperar as informações do banco de dados

**Comment by helenagoulart** [comment]
5
