### ISSUE TITLE
Criar endpoint para pegar os dados de um deputado especifico

### ISSUE THREAD

**Issue by gabrielalbino** [parlamentaqui/gateway#7]
Eu, como Juliana, desejo ter acesso ás informações de um deputado em seu perfil para encontrar as informações sobre ele.

Referências:
- https://www.figma.com/file/UWBRoMSkFlLrO0S0t9yHFc/Parlamentaqui?node-id=1%3A529

Critérios de aceitação: 
- [x] Deve retornar todos os dados para o componente funcionar conforme protótipo do figma.
- [x] Deve receber o id do deputado como parametro e retornar apenas dados do deputado requisitado.
- [x] Deve recuperar as informações do banco de dados

**Comment by helenagoulart** [comment]
5
