### ISSUE TITLE
Criar endpoint para resultados da busca

### ISSUE THREAD

**Issue by gabrielalbino** [parlamentaqui/gateway#8]
US50|Eu, Armim, desejo conseguir ver informações armazenadas sobre os que foi buscado para ficar mais próximo da funcionalidade final.|

Referências:
- https://www.figma.com/file/UWBRoMSkFlLrO0S0t9yHFc/Parlamentaqui?node-id=1%3A529

Critérios de aceitação: 
- [x] Deve receber os filtros no request e retornar os deputados de acordo.
- [x] Deve recuperar as informações do banco de dados

**Comment by helenagoulart** [comment]
8
